[build-system]
requires = [
	"setuptools>=57",
	"wheel>=0.36.0",
	"build>=0.5.1",
]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 106
indent-width = 4

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"

[tool.ruff.lint]
ignore = [
	"B006", # Do not use mutable data structures for argument defaults
	"BLE001", # Do not catch blind exception: `Exception`
	"E722", # bare except
	"I001", # Import block is un-sorted or un-formatted
	"N999", # Invalid module name: 'import'...
	"PLW1510", # `subprocess.run` without explicit `check` argument
	"RET501", # Do not explicitly `return None` in function if it is the only possible return value
	"RUF012", # Mutable default value for class attribute
	"RUF022", # `__all__` is not sorted
	"S110", # `try`-`except`-`pass` detected, consider logging the exception
	"SIM102", # Use a single `if` statement instead of nested `if` statements
	"SIM114", # Combine `if` branches using logical `or` operator
	"SIM905", # Consider using a list literal instead of `str.split`
	"UP031", # Use format specifiers instead of percent format
	"UP032", # Use f-string instead of `format` call
]

[tool.ruff.lint.per-file-ignores]
"protobuf.py"                 = [ "UP045" ]    # Use `X | None` for type annotations
"mmgen/rpc/backends/curl.py"  = [ "ASYNC221" ] # blocking method in async function
"mmgen/tool/*"                = [ "F821" ]     # Undefined name `sstr`

"examples/*" = [ "ASYNC230" ] # open() in async function

"test/overlay/tree/*"        = [ "ALL" ]
"test/modtest_d/cashaddr.py" = [ "F841" ] # assigned to but never used
"test/modtest_d/obj.py"      = [ "F841" ] # assigned to but never used
"test/objattrtest_d/*"       = [ "F401" ] # imported but unused
"test/objtest_d/*"           = [ "F401" ] # imported but unused
"test/modtest_d/dep.py"      = [ "F401" ] # imported but unused
"test/modtest_d/testdep.py"  = [ "F401" ] # imported but unused
"test/cmdtest_d/*" = [
	"ASYNC251", # time.sleep() in async function
	"S102"      # Use of `exec` detected
]
"test/include/common.py" = [
	"F821",   # undefined name 'cfg'
	"PLW0406" # self-import
]
"test/*" = [
	"SIM115",   # open() with context manager
	"ASYNC230", # open() in async func
	"ISC004",   # Unparenthesized implicit string concatenation in collection
	"B018"      # Found useless expression. Either assign it to a variable or remove it.
]

[tool.pylint.format]
indent-string = "\t"
indent-after-paren = 2
max-line-length = 106

[tool.pylint.main]
recursive = true
errors-only = true
jobs = 0
ignore = [
	"data",
]
extension-pkg-allow-list = [
	"mmgen.proto.secp256k1.secp256k1",
	"gmpy2",
]

[tool.pylint."messages control"]
disable = [
	"no-method-argument",
	"no-self-argument",
	"function-redefined",
	"possibly-used-before-assignment",
	"no-member",
]

[tool.pylint.miscellaneous]
notes = ["FIXME", "TODO", "DEBUG", "WIP", "NB"]
