[build-system]
requires = [
	"setuptools>=57",
	"wheel>=0.36.0",
	"build>=0.5.1",
]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 106
indent-width = 4

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"

[tool.ruff.lint]
ignore = [
	"ASYNC221", # blocking method in async function (mmgen/rpc/backends/curl.py)
	"B006", # Do not use mutable data structures for argument defaults
	"B018", # Found useless expression. Either assign it to a variable or remove it.
	"B026", # Star-arg unpacking after a keyword argument is strongly discouraged
	"BLE001", # Do not catch blind exception: `Exception`
	"E722", # bare except
	"I001", # Import block is un-sorted or un-formatted
	"ISC004", # Unparenthesized implicit string concatenation in collection
	"N999", # Invalid module name: 'import'...
	"PLC0206", # Extracting value from dictionary without calling `.items()`
	"PLW1510", # `subprocess.run` without explicit `check` argument
	"RET501", # Do not explicitly `return None` in function if it is the only possible return value
	"RUF012", # Mutable default value for class attribute
	"RUF015", # Prefer `next(s for s in res if 'ersion' in s)` over single element slice
	"RUF022", # `__all__` is not sorted
	"RUF100", # Unused `noqa` directive (non-enabled: `F401`)
	"S102", # Use of `exec` detected
	"S110", # `try`-`except`-`pass` detected, consider logging the exception
	"SIM102", # Use a single `if` statement instead of nested `if` statements
	"SIM103", # Return the negated condition directly
	"SIM114", # Combine `if` branches using logical `or` operator
	"SIM115", # Use a context manager for opening files
	"SIM118", # Use `key in dict` instead of `key in dict.keys()`
	"SIM201", # Use `path.stat().st_mode & S_IWUSR | S_IRUSR != S_IWUSR | S_IRUSR` instead of `not path.stat().st_mode & S_IWUSR | S_IRUSR == S_IWUSR | S_IRUSR`
	"SIM210", # Use `bool(...)` instead of `True if ... else False`
	"SIM401", # Use `d.get(arg, text)` instead of an `if` block
	"SIM905", # Consider using a list literal instead of `str.split`
	"TRY002", # Create your own exception
	"TRY201", # Use `raise` without specifying exception name
	"UP004", # Class `Binary` inherits from `object`
	"UP006", # Use `list` instead of `List` for type annotation
	"UP008", # Use `super()` instead of `super(__class__, self)`
	"UP022", # Prefer `capture_output` over sending `stdout` and `stderr` to `PIPE`
	"UP030", # Use implicit references for positional format fields
	"UP031", # Use format specifiers instead of percent format
	"UP032", # Use f-string instead of `format` call
	"UP034", # Avoid extraneous parentheses
	"UP035", # `typing.List` is deprecated, use `list` instead
	"UP045", # Use `X | None` for type annotations
	"YTT204", # `sys.version_info.minor` compared to integer (python4), compare `sys.version_info` to tuple
]

[tool.ruff.lint.per-file-ignores]
"mmgen/xmrwallet/__init__.py"   = [ "PLC3002" ]      # Lambda expression called directly
"mmgen/tool/*"                  = [ "F821" ]         # Undefined name `sstr`
"mmgen/tool/file.py"            = [ "B008" ]         # function call in dfl args
"mmgen/tool/rpc.py"             = [ "RUF013" ]       # PEP 484 prohibits implicit `Optional`
"mmgen/contrib/keccak.py"       = [ "FURB163" ]      # `math.log` -> `math.log2(state.lanew)`
"examples/*"                    = [ "ASYNC230" ]     # open() in async function

"test/include/common.py" = [
	"F821",   # undefined name 'cfg'
	"PLW0406" # self-import
]
"test/misc/input_func.py"       = [ "F401" ]         # imported but unused
"test/modtest_d/cashaddr.py"    = [ "F841" ]         # assigned to but never used
"test/modtest_d/dep.py"         = [ "F401" ]         # imported but unused
"test/modtest_d/testdep.py"     = [ "F401" ]         # imported but unused
"test/modtest_d/obj.py"         = [ "F841" ]         # assigned to but never used
"test/objtest_d/*"              = [ "F401" ]         # imported but unused
"test/objattrtest_d/*"          = [ "F401" ]         # imported but unused
"test/overlay/fakemods/*"       = [ "F403", "F405" ] # `import *` used
"test/*.py"                     = [ "F401" ]         # imported but unused
"test/colortest.py"             = [ "F403", "F405" ] # `import *` used
"test/tooltest2.py"             = [ "F403", "F405" ] # `import *` used
"test/*"                        = [ "ASYNC230" ]     # open() in async function
"test/cmdtest_d/*"              = [ "ASYNC251" ]     # time.sleep() in async function
"test/overlay/tree/*"           = [ "ALL" ]

[tool.pylint.format]
indent-string = "\t"
indent-after-paren = 2
max-line-length = 106

[tool.pylint.main]
recursive = true
jobs = 0
ignore = [
	"data",
	"wordlist",
	"pyethereum",
	"rlp",
	"main_split.py",
	"tx.py",
]
ignored-modules = [ # ignored for no-member, otherwise checked
	"mmgen.proto.secp256k1.secp256k1",
	"mmgen.term",
	"msvcrt",
	"gmpy2",
]

[tool.pylint."messages control"]
disable = [
	"raw-checker-failed",
	"bad-inline-option",
	"locally-disabled",
	"file-ignored",
	"suppressed-message",
	"useless-suppression",
	"deprecated-pragma",
	"use-symbolic-message-instead",
	"use-implicit-booleaness-not-comparison-to-string",
	"use-implicit-booleaness-not-comparison-to-zero",
	"not-async-context-manager",
# non-default:
	"no-method-argument",
	"function-redefined",
	"method-hidden",
]

[tool.pylint.miscellaneous]
notes = ["FIXME", "TODO", "DEBUG", "WIP"]

[tool.pylint.typecheck]
mixin-class-rgx = """.*[Mm]ixin|\
	^(Hilite|InitErrors|DummyWIF|\
	cfg_file|cfg_file_sample|\
	MoneroMMGenFile|keygen_base|xmr_signable|\
	CmdTestShared|CmdTestSwapMethods|HTTPD|\
	RPC|TxProxyClient|Contract)$"""

ignored-classes = [ # ignored for no-member, otherwise checked
	"argparse.Namespace",
	"optparse.Values",
	"thread._local",
	"_thread._local",
# mmgen:
	"baseconv",
	"deserialized_tx",
	"mmgen.autosign.Signable.base",
	"mmgen.autosign.Autosign", # tx_dir, etc. created dynamically
	"mmgen.rpc.local.RPCClient",
	"mmgen.proto.eth.tx.transaction.Transaction",
	"mmgen.proto.eth.tw.view.EthereumTwView",
	"mmgen.xmrwallet.file.MoneroMMGenTX.Base",
	"mmgen.xmrwallet.file.MoneroWalletOutputsFile.Base",
	"mmgen.xmrwallet.ops.sweep.OpSweep",
	"mmgen.xmrwallet.ops.wallet.OpWallet",
	"mmgen.xmrwallet.ops.label.OpLabel",
	"mmgen.xmrwallet.ops.new.OpNew",
	"mmgen.xmrwallet.ops.txview.OpTxview",
	"mmgen.xmrwallet.file.outputs.MoneroWalletOutputsFile.Base",
	"mmgen.xmrwallet.file.tx.MoneroMMGenTX.Base",
	"MMGenObjectDevTools",
	"MnemonicEntry",
	"MnEntryMode",
	"Sha2",
	"TwRPC",
	"TxInfo",
# test suite:
	"CmdGroupMgr",
	"CmdTestEthBumpMethods",
	"CmdTestEthdevMethods",
	"CmdTestEthSwapMethods",
	"FFI_override",
	"GenTool",
	"Help",
	"Opts",
	"SwapMgrBase",
	"TestHashFunc",
	"VirtBlockDeviceBase",
]
