name: pylint

on:
  push:
    paths:
      - '.github/workflows/pylint.yaml'
      - '**.py'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9","3.10","3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Install Ubuntu package dependencies
      run: |
        sudo apt-get install libsecp256k1-dev

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          setup.cfg

    - name: Install Python dependencies
      run: |
        python3 -m pip install gmpy2 cryptography pynacl ecdsa aiohttp requests pexpect scrypt semantic-version
        python3 -m pip install pycryptodomex pysocks pycoin ipaddress varint pylint
        python3 -m pip install --no-deps py_ecc==1.6.0 mypy_extensions==0.4.1 monero
        python3 setup.py build_ext --inplace

    - name: Check the code with Pylint static code analyzer
      env:
        PYTHONPATH: .
      run: |
        pylint --errors-only mmgen
        pylint --errors-only test
        pylint --errors-only examples
        pylint --errors-only --disable=relative-beyond-top-level test/cmdtest_py_d
